# PKI Sync Client - Secrets Configuration
secrets:
  - secretName: basic_certificate
    saveTo: /var/lib/lxc/pki-authority/rootfs/app/swarm-storage/basic_certificate
  - secretName: basic_privateKey
    saveTo: /var/lib/lxc/pki-authority/rootfs/app/swarm-storage/basic_privateKey
  - secretName: lite_certificate
    saveTo: /var/lib/lxc/pki-authority/rootfs/app/swarm-storage/lite_certificate
  - secretName: lite_privateKey
    saveTo: /var/lib/lxc/pki-authority/rootfs/app/swarm-storage/lite_privateKey
  - secretName: swarmKey
    saveTo: /etc/swarm/swarm.key
